let token=localStorage.vm_admin_token||'';
const $=s=>document.querySelector(s);
const api=async(p,o={})=>{o.headers={...(o.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})};if(o.body){o.headers['Content-Type']='application/json';o.body=JSON.stringify(o.body)}const r=await fetch(p,o),d=await r.json().catch(()=>({}));if(r.status===401&&token){localStorage.removeItem('vm_admin_token');token='';location.reload();throw Error('Admin session expired. Please sign in again.')}if(!r.ok)throw Error(d.detail||'Request failed');return d};
const toast=m=>{const t=$('#toast');t.textContent=m;t.style.display='block';clearTimeout(window.__a);window.__a=setTimeout(()=>t.style.display='none',3000)};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`₹${Number(v||0).toLocaleString('en-IN')}`;
const statusText=s=>({requested:'Buyer order confirmed',farmer_pending_admin:'Farmer accepted · Awaiting admin confirmation',farmer_accepted:'Order accepted',farmer_rejected:'Rejected by farmer',processing:'Tracking enabled',confirmed:'Tracking enabled',shipped:'Shipped',delivered:'Delivered',buyer_cancelled:'Cancelled by buyer',admin_cancelled:'Cancelled by admin'}[s]||String(s||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()));
$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/admin/login',{method:'POST',body:{admin_id:$('#adminId').value,password:$('#adminPassword').value}});token=d.token;localStorage.vm_admin_token=token;openAdmin()}catch(x){toast(x.message)}};
function openAdmin(){$('#adminLogin').hidden=true;$('#adminApp').hidden=false;orders();live()}
$('#adminLogout').onclick=()=>{localStorage.removeItem('vm_admin_token');token='';location.href='/admin'};
let currentAdminView='';
function stopAdminSupportRefresh(){if(adminSupportRefresh){clearInterval(adminSupportRefresh);adminSupportRefresh=null}}
function setAdminView(view){currentAdminView=view;if(view!=='support')stopAdminSupportRefresh()}
$('#navApprovals').onclick=approvals;$('#navOrders').onclick=orders;$('#navVendors').onclick=farmers;$('#navUsers').onclick=usersAdmin;$('#navAdmins').onclick=admins;$('#navSupport').onclick=adminSupport;
async function approvals(){setAdminView('approvals');const [pending,published]=await Promise.all([api('/api/admin/pending'),api('/api/admin/crops/published')]);const pendingHtml=pending.length?pending.map(x=>`<div class="panel review adminReviewCard"><div class="reviewInfo">${x.photo?`<img class="reviewPhoto" src="${x.photo}">`:''}<div><h2>${esc(x.name)}</h2><div class="farmerDetailBox"><small class="personLabel">FARMER</small><b>${esc(x.farmer_name)}</b><span>${esc(x.farmer_phone)}</span><span>${esc([x.location,x.address_line,x.village,x.mandal,x.district,x.state,x.pincode,x.landmark].filter(Boolean).join(', '))}</span></div><p>${x.quantity_kg} kg submitted · expected ${money(x.expected_price)}/kg · ${esc(x.quality)}</p></div></div><div class="actions"><button class="yes" onclick="inspect(${x.id})">Visit Farm · Verify & Finalize Price</button><button class="farmerRejectBtn" onclick="rejectCropPage(${x.id})">Reject</button></div></div>`).join(''):'<div class="panel empty">No pending crops.</div>';const pubHtml=published.length?published.map(x=>`<div class="panel publishedCropRow"><div class="publishedCropInfo">${x.photo?`<img src="${x.photo}">`:'<span class="cropPlaceholder">🌾</span>'}<div><b>${esc(x.name)}</b><small>${esc(x.category)} · ${x.available_kg} kg available · ${money(x.market_price)}/kg</small><span>${esc(x.farmer_name)} · ${esc(x.farmer_phone)}</span></div></div><div class="publishedCropActions"><button class="secondaryBtn" onclick="editMarketCropPage(${x.id})">Edit Crop & Price</button><button class="dangerBtn" onclick="removeMarketCropPage(${x.id})">Remove from Marketplace</button></div></div>`).join(''):'<div class="panel empty">No published crops.</div>';$('#adminContent').innerHTML=`<span class="eyebrow">CROP APPROVALS</span><h1 class="title">Farm inspections</h1>${pendingHtml}<h2 class="sectionTitle adminSectionTitle">Published Marketplace Items</h2><p class="lead">Admin can remove any published crop so it immediately disappears from the buyer marketplace.</p><div class="publishedCropList">${pubHtml}</div>`}
window.inspect=async id=>{const r=await api('/api/admin/pending'),x=r.find(z=>z.id==id);if(!x)return toast('Crop not found or already processed');$('#adminContent').innerHTML=`<div class="pageBar"><button class="secondaryBtn" onclick="approvals()">← Back</button></div><h1 class="title">Verify crop & final price</h1><div class="panel review"><div><h2>${esc(x.name)}</h2><div class="farmerDetailBox"><b>${esc(x.farmer_name)}</b><span>${esc(x.farmer_phone)}</span><span>${esc([x.location,x.address_line,x.village,x.mandal,x.district,x.state,x.pincode,x.landmark].filter(Boolean).join(', '))}</span></div></div></div><form id="if" class="form"><label>Verified quantity<input name="q" type="number" min="10" max="${x.quantity_kg}" value="${x.quantity_kg}" required></label><label>Verified quality<input name="quality" value="${esc(x.quality)}" required></label><label>Final price ₹/kg<input name="price" type="number" step="0.01" min="0.01" required></label><label>Inspection note<input name="note"></label><div class="addressActions wide"><button class="secondaryBtn" type="button" onclick="approvals()">Cancel</button><button class="yes" type="submit">Approve & Publish</button></div></form>`;$('#if').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api(`/api/admin/crops/${id}`,{method:'PATCH',body:{action:'approve',inspected_quantity:Number(f.get('q')),inspected_quality:String(f.get('quality')),market_price:Number(f.get('price')),admin_note:String(f.get('note'))}});toast('Crop approved');approvals()}catch(x){toast(x.message)}}};
window.rejectCropPage=async id=>{const r=await api('/api/admin/pending');const x=r.find(z=>z.id==id);if(!x)return toast('Crop not found');$('#adminContent').innerHTML=`<div class="pageBar"><button class="secondaryBtn" onclick="approvals()">← Back to Crop Approvals</button></div><span class="eyebrow">CROP REJECTION</span><h1 class="title">Reject ${esc(x.name)}</h1><div class="panel rejectCropPage"><div class="farmerDetailBox"><small class="personLabel">FARMER</small><b>${esc(x.farmer_name)}</b><span>${esc(x.farmer_phone)}</span><span>${x.quantity_kg} kg · ${esc(x.quality)}</span></div><form id="rejectCropForm" class="form singleForm"><label class="wide">Reason for rejection<textarea name="reason" required minlength="3" placeholder="Explain why this crop is being rejected so the farmer can correct it."></textarea></label><div class="addressActions wide"><button type="button" class="secondaryBtn" onclick="approvals()">Cancel</button><button type="submit" class="dangerBtn">Reject Crop</button></div></form></div>`;$('#rejectCropForm').onsubmit=async e=>{e.preventDefault();const reason=new FormData(e.target).get('reason').trim();try{await api(`/api/admin/crops/${id}`,{method:'PATCH',body:{action:'reject',admin_note:reason}});toast('Crop rejected');approvals()}catch(err){toast(err.message)}}};
window.rejectCrop=window.rejectCropPage;

window.editMarketCropPage=async id=>{const rows=await api('/api/admin/crops/published');const x=rows.find(z=>Number(z.id)===Number(id));if(!x)return toast('Crop not found');$('#adminContent').innerHTML=`<div class="pageBar"><button class="secondaryBtn" onclick="approvals()">← Back to Crop Approvals</button></div><span class="eyebrow">MARKET UPDATE</span><h1 class="title">Edit crop & market price</h1><p class="lead">Update the published crop whenever the market changes. Existing orders keep their original booked price.</p><form id="editMarketCropForm" class="form adminCropEditForm"><label>Crop name<input name="name" value="${esc(x.name)}" required></label><label>Category<input name="category" value="${esc(x.category)}" required></label><label>Available quantity (kg)<input name="available_kg" type="number" min="0" step="0.01" value="${x.available_kg}" required></label><label>Quality / grade<input name="quality" value="${esc(x.quality)}" required></label><label>Harvest date<input name="harvest_date" type="date" value="${esc(x.harvest_date||'')}" required></label><label>Current market price (₹/kg)<input name="market_price" type="number" min="0.01" step="0.01" value="${x.market_price}" required></label><label class="wide">Crop details<textarea name="details">${esc(x.details||'')}</textarea></label><label class="wide">Admin update note<textarea name="admin_note" placeholder="Example: Price increased based on today's local market rate.">${esc(x.admin_note||'')}</textarea></label><div class="addressActions wide"><button type="button" class="secondaryBtn" onclick="approvals()">Cancel</button><button type="submit" class="primary">Save Changes</button></div></form>`;$('#editMarketCropForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);try{await api(`/api/admin/crops/${id}/edit`,{method:'PATCH',body:{name:String(fd.get('name')),category:String(fd.get('category')),available_kg:Number(fd.get('available_kg')),quality:String(fd.get('quality')),harvest_date:String(fd.get('harvest_date')),details:String(fd.get('details')||''),market_price:Number(fd.get('market_price')),admin_note:String(fd.get('admin_note')||'')}});toast('Crop and market price updated');approvals()}catch(err){toast(err.message)}}};
window.removeMarketCropPage=async id=>{const rows=await api('/api/admin/crops/published');const x=rows.find(z=>Number(z.id)===Number(id));if(!x)return toast('Crop not found');$('#adminContent').innerHTML=`<div class="pageBar"><button class="secondaryBtn" onclick="approvals()">← Back to Crop Approvals</button></div><span class="eyebrow">REMOVE FROM MARKETPLACE</span><h1 class="title">Remove ${esc(x.name)}</h1><div class="panel removeCropPage"><div class="removeCropSummary">${x.photo?`<img src="${x.photo}">`:'<span class="cropPlaceholder">🌾</span>'}<div><h2>${esc(x.name)}</h2><p>${esc(x.category)} · ${x.available_kg} kg available · ${money(x.market_price)}/kg</p><div class="farmerDetailBox"><small class="personLabel">FARMER</small><b>${esc(x.farmer_name)}</b><span>${esc(x.farmer_phone)}</span><span>${esc([x.location,x.address_line,x.village,x.mandal,x.district,x.state,x.pincode,x.landmark].filter(Boolean).join(', '))}</span></div></div></div><div class="adminWarning">This crop will disappear from the buyer marketplace, but the farmer crop record will remain in the farmer dashboard with this removal reason.</div><form id="removeCropForm" class="form singleForm"><label class="wide">Reason for removal<textarea name="reason" required minlength="3" placeholder="Explain why this crop is being removed from the marketplace."></textarea></label><div class="addressActions wide"><button type="button" class="secondaryBtn" onclick="approvals()">Cancel</button><button type="submit" class="dangerBtn">Remove from Marketplace</button></div></form></div>`;$('#removeCropForm').onsubmit=async e=>{e.preventDefault();const reason=String(new FormData(e.target).get('reason')||'').trim();if(reason.length<3)return toast('Please enter a removal reason');try{await api(`/api/admin/crops/${id}/remove`,{method:'PATCH',body:{reason}});toast('Crop removed from buyer marketplace');approvals()}catch(err){toast(err.message)}}};
window.removeMarketCrop=window.removeMarketCropPage;
let adminOrderTab='active';
function renderAdminOrderCard(b){return `<article class="panel adminOrderCard"><div class="adminOrderHead"><div><span class="eyebrow">ORDER #${b.id}</span><h2>${esc(b.crop_name)}</h2><p>${b.quantity_kg} kg · ${money(b.final_price)}/kg · <b>${money(b.amount)}</b></p></div><span class="badge adminStatusBadge">${esc(statusText(b.status))}</span></div><div class="adminOrderMeta"><span><small>Harvest date</small><b>${esc(b.harvest_date||'—')}</b></span><span><small>Delivery</small><b>Home delivery</b></span><span><small>Tracking</small><b>${['processing','shipped','delivered'].includes(b.status)?'Enabled':'Not enabled'}</b></span></div><div class="personGrid"><div class="personBox"><small class="personLabel">BUYER</small><b>${esc(b.buyer_name)}</b><span>${esc(b.buyer_phone)}</span><span>${esc(b.delivery_address||'')}</span></div><div class="personBox"><small class="personLabel">FARMER</small><b>${esc(b.farmer_name)}</b><span>${esc(b.farmer_phone)}</span><span>${esc(b.crop_location||'')}</span></div></div>${['farmer_rejected','admin_cancelled','buyer_cancelled'].includes(b.status)?`<div class="rejectReason"><b>Note:</b> ${esc(b.farmer_note||'')}</div>`:''}<div class="actions adminOrderActions">${b.status==='farmer_pending_admin'?`<button class="primary" onclick="move(${b.id},'farmer_accepted')">Confirm Order</button>`:''}${b.status==='farmer_accepted'?`<button class="primary" onclick="move(${b.id},'processing')">Enable Tracking</button>`:''}${b.status==='processing'||b.status==='confirmed'?`<button class="primary" onclick="move(${b.id},'shipped')">Mark Shipped</button>`:''}${b.status==='shipped'?`<div class="deliveryOtpAdminBox"><label>Buyer Delivery OTP<input id="deliveryOtp-${b.id}" inputmode="numeric" maxlength="6" placeholder="Enter 6-digit OTP"></label><button class="primary" onclick="verifyDeliveryOtp(${b.id})">Verify OTP & Mark Delivered</button><small>Ask the buyer for this OTP only after the buyer has received the order.</small></div>`:''}${!['delivered','farmer_rejected','buyer_cancelled','admin_cancelled'].includes(b.status)?`<button class="dangerBtn" onclick="cancelAdmin(${b.id})">Cancel Order</button>`:''}<button class="secondaryBtn" onclick="deleteAdminOrder(${b.id})">Delete Order</button></div></article>`}
async function orders(tab=adminOrderTab){setAdminView('orders');adminOrderTab=tab;const r=await api('/api/admin/bookings');const active=r.filter(b=>b.status!=='delivered');const delivered=r.filter(b=>b.status==='delivered');const rows=adminOrderTab==='delivered'?delivered:active;const html=rows.length?rows.map(renderAdminOrderCard).join(''):`<div class="panel empty">${adminOrderTab==='delivered'?'No delivered orders yet.':'No active orders.'}</div>`;$('#adminContent').innerHTML=`<span class="eyebrow">ORDERS</span><h1 class="title">Order monitoring</h1><p class="lead">Admin confirms farmer acceptance and controls tracking, shipping, delivery, or cancellation.</p><div class="adminOrderTabs"><button class="${adminOrderTab==='active'?'active':''}" onclick="orders('active')"><span>Active Orders</span><b>${active.length}</b></button><button class="${adminOrderTab==='delivered'?'active':''}" onclick="orders('delivered')"><span>Delivered Orders</span><b>${delivered.length}</b></button></div><div class="adminOrderList">${html}</div>`}
window.orders=orders;
window.move=async(id,s)=>{try{await api(`/api/admin/bookings/${id}/status`,{method:'PATCH',body:{status:s}});toast(s==='farmer_accepted'?'Order confirmed by admin':'Status updated');orders()}catch(x){toast(x.message)}};

window.verifyDeliveryOtp=async id=>{const el=document.getElementById(`deliveryOtp-${id}`);const otp=String(el?.value||'').trim();if(!/^\d{6}$/.test(otp))return toast('Enter the 6-digit OTP given by the buyer');try{await api(`/api/admin/bookings/${id}/verify-delivery-otp`,{method:'POST',body:{otp}});toast('OTP verified. Order marked Delivered');orders()}catch(x){toast(x.message)}};
window.cancelAdmin=async id=>{const reason=prompt('Reason for cancelling this order:');if(reason===null)return;try{await api(`/api/admin/bookings/${id}/status`,{method:'PATCH',body:{status:'admin_cancelled',reason:reason.trim()}});toast('Order cancelled');orders()}catch(x){toast(x.message)}};
window.deleteAdminOrder=async id=>{if(!confirm('Permanently delete this order? This cannot be undone.'))return;try{await api(`/api/admin/bookings/${id}`,{method:'DELETE'});toast('Order deleted');orders()}catch(x){toast(x.message)}};
async function farmers(){setAdminView('farmers');const r=await api('/api/admin/vendors');$('#adminContent').innerHTML=`<span class="eyebrow">FARMERS</span><h1 class="title">List of Farmers</h1><div class="table farmerTable"><div class="row"><b>Farmer</b><b>Phone</b><b>Crops</b><b>Accepted orders</b><b>Revenue</b></div>${r.length?r.map(v=>`<div class="row"><span>${esc(v.name)}</span><span>${esc(v.phone)}</span><span>${v.crops}</span><span>${v.accepted_orders}</span><span>${money(v.revenue)}</span></div>`).join(''):'<div class="panel empty">No farmers yet.</div>'}</div>`}

async function usersAdmin(){
  setAdminView('users');
  const rows=await api('/api/admin/users');
  const html=rows.length?rows.map(u=>`<article class="panel adminUserCard"><div><span class="eyebrow">USER #${u.id}</span><h3>${esc(u.name)}</h3><p>${esc(u.phone)} · ${esc(u.email||'No email')}</p><small>Login roles: ${esc((u.login_roles||[]).join(', ')||u.registered_role)} · ${u.verified?'Verified':'Not verified'}</small></div><div class="publishedCropActions"><button class="secondaryBtn" onclick="editAdminUser(${u.id})">Edit User</button><button class="dangerBtn" onclick="deleteAdminUser(${u.id})">Delete User & Data</button></div></article>`).join(''):'<div class="panel empty">No buyer/farmer accounts yet.</div>';
  $('#adminContent').innerHTML=`<span class="eyebrow">USER MANAGEMENT</span><h1 class="title">Buyers & Farmers</h1><p class="lead">Admin can view, edit, verify, or permanently remove buyer/farmer accounts and their marketplace data.</p><div class="adminUserList">${html}</div>`;
}
window.usersAdmin=usersAdmin;
window.editAdminUser=async id=>{const rows=await api('/api/admin/users'),u=rows.find(x=>Number(x.id)===Number(id));if(!u)return toast('User not found');$('#adminContent').innerHTML=`<div class="pageBar"><button class="secondaryBtn" onclick="usersAdmin()">← Back</button></div><h1 class="title">Edit user</h1><form id="adminUserEditForm" class="form singleForm"><label>Name<input name="name" value="${esc(u.name)}" required></label><label>Email<input name="email" type="email" value="${esc(u.email||'')}"></label><label><input name="verified" type="checkbox" ${u.verified?'checked':''}> Verified account</label><div class="addressActions wide"><button type="button" class="secondaryBtn" onclick="usersAdmin()">Cancel</button><button type="submit" class="primary">Save changes</button></div></form>`;$('#adminUserEditForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api(`/api/admin/users/${id}`,{method:'PATCH',body:{name:String(f.get('name')||'').trim(),email:String(f.get('email')||'').trim()||null,verified:f.get('verified')==='on'}});toast('User updated');usersAdmin()}catch(err){toast(err.message)}}};
window.deleteAdminUser=async id=>{if(!confirm('Permanently delete this buyer/farmer and all related crops, orders, addresses, support messages and sessions?'))return;try{await api(`/api/admin/users/${id}`,{method:'DELETE'});toast('User and related data deleted');usersAdmin()}catch(err){toast(err.message)}};

async function admins(){
  setAdminView('admins');
  const rows=await api('/api/admin/admins');
  const list=rows.length?rows.map(a=>`<div class="adminAccountRow"><div><b>${esc(a.name)}</b><span>Admin ID: ${esc(a.admin_id)}</span>${a.primary?'<small>Primary admin</small>':'<small>Additional admin</small>'}</div>${a.primary?'':`<button class="dangerBtn" onclick="removeAdmin(${a.id})">Remove</button>`}</div>`).join(''):'<div class="panel empty">No admin accounts.</div>';
  $('#adminContent').innerHTML=`<span class="eyebrow">ADMIN MANAGEMENT</span><h1 class="title">Admins</h1><p class="lead">Create additional admin accounts. Each admin signs in with their own Admin ID and password.</p><div class="panel adminCreatePanel"><h2>Add new admin</h2><form id="addAdminForm" class="form singleForm"><label>Admin name<input name="name" required autocomplete="off" placeholder="Enter admin name"></label><label>Admin ID<input name="admin_id" required minlength="3" autocomplete="off" placeholder="Create admin ID"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="new-password" placeholder="Create password"></label><div class="addressActions wide"><button type="submit" class="primary">Add Admin</button></div></form></div><h2 class="sectionTitle adminSectionTitle">Existing admins</h2><div class="adminAccountList">${list}</div>`;
  $('#addAdminForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/admin/admins',{method:'POST',body:{name:String(f.get('name')||'').trim(),admin_id:String(f.get('admin_id')||'').trim(),password:String(f.get('password')||'')}});toast('Admin added successfully');admins()}catch(err){toast(err.message)}};
}
window.admins=admins;
window.removeAdmin=async id=>{if(!confirm('Remove this admin account?'))return;try{await api(`/api/admin/admins/${id}`,{method:'DELETE'});toast('Admin removed');admins()}catch(err){toast(err.message)}};



let adminSupportRefresh=null;
function adminSupportTime(v){if(!v)return '';try{return new Date(v).toLocaleString()}catch{return v}}
function adminSupportMessages(tk){return (tk.messages||[]).map(m=>`<div class="supportMessage ${m.sender_role==='admin'?'fromAdmin':'fromUser'}"><div><b>${m.sender_role==='admin'?'Admin':esc(tk.user_name)}</b><small>${esc(adminSupportTime(m.created_at))}</small></div><p>${esc(m.message)}</p></div>`).join('')}
async function adminSupport(){
  setAdminView('support');
  stopAdminSupportRefresh();
  const rows=await api('/api/admin/support/tickets');
  if(currentAdminView!=='support')return;
  const open=rows.filter(x=>x.status==='open'),closed=rows.filter(x=>x.status==='closed');
  const html=rows.length?rows.map(tk=>`<article class="panel supportTicket ${tk.status}"><div class="supportTicketHead"><div><span class="eyebrow">TICKET #${tk.id} · ${esc(tk.category.toUpperCase())}</span><h2>${esc(tk.subject)}</h2><p>${esc(tk.user_name)} · ${esc(tk.user_role)} · ${esc(tk.user_phone)}</p><small>Updated ${esc(adminSupportTime(tk.updated_at))}</small></div><span class="badge">${esc(tk.status.toUpperCase())}</span></div><div class="supportChat">${adminSupportMessages(tk)}</div>${tk.status==='open'?`<form class="supportReplyForm" onsubmit="adminSupportReply(event,${tk.id})"><input name="message" required maxlength="2000" placeholder="Reply to ${esc(tk.user_name)}…"><button class="primary" type="submit">Reply</button></form><button class="secondaryBtn supportCloseBtn" onclick="adminSupportStatus(${tk.id},'closed')">Close ticket</button>`:`<button class="secondaryBtn" onclick="adminSupportStatus(${tk.id},'open')">Reopen ticket</button>`}</article>`).join(''):'<div class="panel empty">No live support requests yet.</div>';
  $('#adminContent').innerHTML=`<span class="eyebrow">LIVE SUPPORT</span><h1 class="title">Customer & Farmer Support</h1><p class="lead">Reply to Buyer and Farmer support requests and close them when resolved.</p><div class="supportStats"><span><b>${open.length}</b> Open</span><span><b>${closed.length}</b> Closed</span></div><div class="supportTicketList">${html}</div>`;
  if(currentAdminView==='support')adminSupportRefresh=setInterval(()=>{if(currentAdminView==='support')adminSupport().catch(()=>{})},8000)
}
window.adminSupport=adminSupport;
window.adminSupportReply=async(e,id)=>{e.preventDefault();const input=e.target.elements.message,msg=String(input.value||'').trim();if(!msg)return;try{await api(`/api/admin/support/tickets/${id}/messages`,{method:'POST',body:{message:msg}});input.value='';toast('Reply sent');adminSupport()}catch(err){toast(err.message)}};
window.adminSupportStatus=async(id,status)=>{try{await api(`/api/admin/support/tickets/${id}/status`,{method:'PATCH',body:{status}});toast(status==='closed'?'Support ticket closed':'Support ticket reopened');adminSupport()}catch(err){toast(err.message)}};

function live(){try{const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/admin`);ws.onmessage=()=>toast('Live market update received')}catch{}}
(async()=>{if(token)try{const m=await api('/api/me');if(m.role!=='superadmin')throw Error();openAdmin()}catch{localStorage.removeItem('vm_admin_token')}})();
